services:
  - type: web
    name: telegram-notion-bot
    env: python
    region: oregon
    plan: free
    runtime: python
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: python telegram_notion_bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: NOTION_TOKEN  
        sync: false
      - key: DATABASE_ID
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.9"
